### ISSUE TITLE
训练问题

### ISSUE THREAD

**Issue by lixixin** [HighwayWu/InpaintingForensics#3]
您好，我看了你的代码，训练样本是48000的话，每一个epoch都会有4次val。这种框架的训练每一个epoch都会自己重新训练一遍吗？因为我在跑这个代码的时候，每次迭代loss和auc都像是重新开始一样，比如我第一个epoch可以跑到auc0.77，但是第二个epoch开始就又变成0.48，接着后面的结果居然越来越差（这里可能是因为我使用的是我自己数据，并且我改了下数据接口）。

**Comment by HighwayWu** [comment]
您好！
每次训练都是在上一轮的基础上训练的。只是每次val之后记录的指标会清空而已。这种情况还是请您再检查一下训练流程/数据集是否无误吧。谢谢。

**Comment by lixixin** [comment]
我不知道这算不算个bug，我发现当我的train_num不是batch_size的倍数的时候，就会出现这种情况。也许你可以试一下。

**Comment by lixixin** [comment]
您好，我还有一个问题，在您的代码class IID_Model(nn.Module)这个类中有两个模型，IID和IID_NAS，默认使用第一个。这两个训练后的性能会有很大差距吗？
当我想使用第二个进行训练时候报错：
Traceback (most recent call last):
  File "/home/1/Codes/Pytorch_codes/InpaintingForensics-master/main.py", line 846, in <module>
    model.train()
  File "/home/1/Codes/Pytorch_codes/InpaintingForensics-master/main.py", line 727, in train
    Mo, gen_loss = self.giid_model.process(Ii, Mg)
  File "/home/1/Codes/Pytorch_codes/InpaintingForensics-master/main.py", line 616, in process
    Mo = self(Ii)
  File "/home/1/anaconda3/envs/deeplearn/lib/python3.6/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/1/Codes/Pytorch_codes/InpaintingForensics-master/main.py", line 623, in forward
    return self.gen(Ii)
  File "/home/1/anaconda3/envs/deeplearn/lib/python3.6/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/1/anaconda3/envs/deeplearn/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 161, in forward
    outputs = self.parallel_apply(replicas, inputs, kwargs)
  File "/home/1/anaconda3/envs/deeplearn/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 171, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/home/1/anaconda3/envs/deeplearn/lib/python3.6/site-packages/torch/nn/parallel/parallel_apply.py", line 86, in parallel_apply
    output.reraise()
  File "/home/1/anaconda3/envs/deeplearn/lib/python3.6/site-packages/torch/_utils.py", line 428, in reraise
    raise self.exc_type(msg)
TypeError: Caught TypeError in replica 0 on device 0.
Original Traceback (most recent call last):
  File "/home/1/anaconda3/envs/deeplearn/lib/python3.6/site-packages/torch/nn/parallel/parallel_apply.py", line 61, in _worker
    output = module(*input, **kwargs)
  File "/home/1/anaconda3/envs/deeplearn/lib/python3.6/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/1/Codes/Pytorch_codes/InpaintingForensics-master/main.py", line 565, in forward
    x = cell(x, genotype[i])
TypeError: 'NoneType' object is not subscriptable


Process finished with exit code 1
